default_platform(:ios)

desc "Export colors from Figma"
lane :export_colors do
  Dir.chdir("../") do
    sh "Pods/FigmaExport/Release/figma-export colors"
  end
end

desc "Export icons from Figma"
lane :export_icons do
  Dir.chdir("../") do
    sh "Pods/FigmaExport/Release/figma-export icons"
  end
end

desc "Export images с Figma"
lane :export_images do
  Dir.chdir("../") do
    sh "Pods/FigmaExport/Release/figma-export images"
  end
end